name: Haxe CI

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: krdlab/setup-haxe@v1
      with:
        haxe-version: 4.1.2
    - name: Set up Dependencies
      run: |
        haxelib install lime --quiet
        haxelib install openfl --quiet
        haxelib install actuate --quiet
        haxelib install feathersui --quiet
    - name: Build counter
      working-directory: counter
      run: |
        haxelib run openfl build neko
        haxelib run openfl build html5
        haxelib run openfl build flash
    - name: Build crud
      working-directory: crud
      run: |
        haxelib run openfl build neko
        haxelib run openfl build html5
        haxelib run openfl build flash
    - name: Build flight-booker
      working-directory: flight-booker
      run: |
        haxelib run openfl build neko
        haxelib run openfl build html5
        haxelib run openfl build flash
    - name: Build temperature-converter
      working-directory: temperature-converter
      run: |
        haxelib run openfl build neko
        haxelib run openfl build html5
        haxelib run openfl build flash
    - name: Build timer
      working-directory: timer
      run: |
        haxelib run openfl build neko
        haxelib run openfl build html5
        haxelib run openfl build flash
